openapi: 3.0.1
info:
  title: STD21018
  description: 'Hello word !'
  version: 1.0.0
servers:
  - url: https://STD21018
tags:
  - name: Student
  - name: Courses
paths:
  /student:
    get:
      tags:
        - Student
      summary: Get all students
      description: Get all students with details
      parameters:
        - name: page
          in: query
          style: form
          explode: true
          schema:
            type: integer
        - name: page_size
          in: query
          style: form
          explode: true
          required: true
          schema:
            type: integer
      responses:
        200:
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string

        400:
          description: Bad request
    post:
      tags:
        - Student
      summary: Create new students
      description: Create new students from an array
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
      responses:
        200:
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
components:
  schemas:
    CreateStudent:
      type: object
    Student:
      type: object